import { 
  LayoutDashboard, 
  Rocket, 
  Package, 
  ShieldCheck, 
  Briefcase, 
  ShoppingCart, 
  Truck, 
  CreditCard, 
  Headphones, 
  Puzzle, 
  Globe, 
  Lock, 
  HelpCircle,
  LucideIcon
} from "lucide-react"

export type DocPage = {
  title: string
  slug: string
  content: string
}

export type DocSection = {
  title: string
  slug: string
  icon: LucideIcon
  items: DocPage[]
}

export const docsData: DocSection[] = [
  {
    title: "Panoramica",
    slug: "panoramica",
    icon: LayoutDashboard,
    items: [
      { 
        title: "Benvenuto nel Manuale", 
        slug: "benvenuto", 
        content: `# Benvenuto nel Manuale del Seller\n\nLa guida completa per vendere, gestire ed esportare il Made in Italy nel mondo con Ida. Qui troverai tutte le risorse necessarie per ottimizzare il tuo business B2B internazionale.` 
      },
      { 
        title: "Come usare la documentazione", 
        slug: "come-usare", 
        content: `# Come usare la documentazione\n\n## Struttura delle pagine\nOgni pagina della documentazione segue una struttura coerente per facilitare la consultazione rapida:\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">A cosa serve</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Introduzione che spiega l'obiettivo della funzionalità o processo descritto.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Prerequisiti</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Cosa devi aver completato o configurato prima di procedere con le istruzioni.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Procedura</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Guida operativa step-by-step con istruzioni dettagliate per raggiungere l'obiettivo.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">FAQ & Casi frequenti</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Domande, risposte rapide e scenari comuni (edge cases) su come gestire eventuali eccezioni.</p>\n  </div>\n</div>\n\n## Navigazione\nPuoi navigare la documentazione in diversi modi:\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Sidebar laterale</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">La sidebar sinistra mostra l'albero completo e si espande al click.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Indice pagina</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">La colonna destra mostra i titoli della pagina corrente per saltare subito al punto giusto.</p>\n  </div>\n</div>`
      },
      { 
        title: "Glossario", 
        slug: "glossario", 
        content: `# Glossario\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">KYB (Know Your Business)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Processo di verifica aziendale obbligatorio per certificare la validità della P.IVA e della società.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">MOQ (Minimum Order Quantity)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Quantità minima ordinabile impostata dal seller per un prodotto o una variante.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">RFQ (Request for Quotation)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Richiesta di preventivo personalizzato inviata dal buyer per volumi elevati o condizioni speciali.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Net Terms</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Termini di pagamento dilazionato (es. 30, 60 o 90 giorni) concessi ai buyer B2B qualificati.</p>\n  </div>\n</div>`
      },
      { 
        title: "Ruoli e permessi", 
        slug: "ruoli-permessi", 
        content: `# Ruoli e permessi\n\n## Ruoli Seller\nAll'interno di un account seller, puoi assegnare diversi ruoli ai membri del team per garantire sicurezza e privacy:\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Owner (Proprietario)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Accesso completo. Gestisce abbonamento, dati aziendali legali, utenti, ruoli e riceve i payout.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Admin</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Accesso quasi completo. Gestisce catalogo, ordini, spedizioni e membri del team (escluso Owner).</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Catalog Manager</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Focalizzato sui prodotti. Può creare varianti, gestire inventario e media, ma non vede ordini o finanze.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Order Manager</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Logistica pura. Gestisce ordini, genera etichette, comunica con i buyer e processa i resi.</p>\n  </div>\n</div>\n\n## Ruoli Buyer e Partner\nI buyer con Company Account e i partner tecnici (es. RINA, Prometheux.ai) hanno accessi specifici configurati per operare nel rispetto della privacy e dei flussi di approvazione.`
      },
    ]
  },
  {
    title: "Inizia a vendere",
    slug: "seller",
    icon: Rocket,
    items: [
      { 
        title: "Overview Seller", 
        slug: "overview", 
        content: `# Overview Seller\n\n## Perché vendere su Ida\nIda è il marketplace B2B dedicato esclusivamente al Made in Italy autentico. A differenza di altri marketplace generalisti, offriamo un ecosistema verticale.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Buyer verificati</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Solo aziende con verifica KYB completata. Nessun consumatore privato, solo professionisti del settore.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Focus B2B</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Strumenti progettati per le aziende: MOQ, tier pricing, RFQ, net terms e gestione di listini multipli.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Compliance Integrata</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Supporto completo per l'export internazionale: codici doganali, documentazione e certificazioni Made in Italy.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Ecosistema Partner</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Integrazioni native con RINA, Prometheux.ai e Translated.com per scalare il tuo business senza sforzo.</p>\n  </div>\n</div>\n\n## I grandi vantaggi\n\n> **Success**\n> **Espansione internazionale**\n> Raggiungi buyer in oltre 50 paesi senza investire in sales team locali. Ida gestisce localizzazione, conversioni valuta e la compliance export.\n\n> **Info**\n> **Protezione del brand & Zero rischio credito**\n> Ida Genesis verifica l'autenticità di ogni prodotto, proteggendo la reputazione del Made in Italy. Inoltre, Ida gestisce gli incassi anticipando il capitale: incassi garantiti prima di spedire.`
      },
      { 
        title: "Requisiti necessari", 
        slug: "requisiti", 
        content: `# Requisiti necessari\n\nPrima di avviare l'onboarding, assicurati che la tua azienda e i tuoi prodotti rispettino i severi criteri di ammissibilità del marketplace Ida.\n\n## Regole di ammissibilità\n\n<div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Made in Italy</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">È obbligatorio che l'articolo sia ideato, lavorato e confezionato in Italia.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Azienda Italiana</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Richiesta P.IVA italiana, visura regolare e un conto IBAN aziendale.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Spedizione Origin</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">La merce deve partire esclusivamente da un magazzino in Italia.</p>\n  </div>\n</div>\n\n## Performance e SLA richieste\nPer garantire standard eccellenti ai buyer globali, monitoriamo questi requisiti operativi continui:\n- **Tasso di risposta:** > 90% entro 24 ore lavorative.\n- **Spedizioni puntuali:** > 95% di rispetto dei tempi dichiarati in scheda prodotto.\n- **Tasso di difetti / Resi:** < 1% sul volume totale degli ordini.`
      },
      { 
        title: "Onboarding step-by-step", 
        slug: "onboarding-step-by-step", 
        content: `# Onboarding step-by-step\n\nIl processo per diventare Seller su Ida è guidato e automatizzato. Segui questi passaggi per iniziare a vendere.\n\n<div className="steps-list">\n  <div className="step-item" data-step="1">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Registrazione Account</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Inserisci l'email aziendale, crea una password sicura e accetta Termini e Condizioni.</p>\n  </div>\n  <div className="step-item" data-step="2">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Verifica KYB Automatica</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Inserisci la tua P.IVA: il sistema verificherà in tempo reale l'azienda presso la Camera di Commercio e i database antiriciclaggio.</p>\n  </div>\n  <div className="step-item" data-step="3">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Setup Profilo Aziendale</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Completa i dati di base: indirizzo sede, IBAN per i payout, logo aziendale e settori merceologici.</p>\n  </div>\n  <div className="step-item" data-step="4">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Impostazione Mercati & Logistica</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Seleziona in quali nazioni intendi vendere e configura le tue preferenze per i corrieri (propri o Ida Shipping).</p>\n  </div>\n  <div className="step-item" data-step="5">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Caricamento Catalogo</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Inserisci il primo prodotto (manualmente o via CSV) per avviare il processo di revisione "Ida Genesis".</p>\n  </div>\n  <div className="step-item" data-step="6">\n    <h4 className="text-[15px] font-semibold text-zinc-900 dark:text-white mb-1">Approvazione e Go Live</h4>\n    <p className="text-[14px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Appena il primo articolo supera il controllo Made in Italy, il tuo negozio sarà visibile ai buyer internazionali.</p>\n  </div>\n</div>`
      },
      { 
        title: "Impostazioni base e Mercati", 
        slug: "impostazioni-mercati", 
        content: `# Impostazioni e Mercati\n\nNella tua dashboard potrai configurare le basi operative per internazionalizzare il business.\n\n## Configurazioni principali\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Valute e Prezzi</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Imposta i prezzi nella tua valuta base (EUR). Ida si occuperà della conversione automatica per il buyer finale.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Lingue e Localizzazione</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">L'interfaccia si traduce in automatico in base al paese del buyer (grazie a Lara AI / Translated). Tu gestisci tutto comodamente in Italiano.</p>\n  </div>\n</div>\n\n## Attivazione Paesi (Geografie)\nIda permette di sbloccare o bloccare mercati con un clic, raggruppati in:\n- **Europa (UE)**: Spedizioni facili, Reverse Charge IVA, no dogana.\n- **Europa (Extra-UE)**: UK, Svizzera, Norvegia (richiesta dogana base).\n- **Nord America**: USA, Canada (gestione DDP/DDU, normative FDA).\n- **Asia & Medio Oriente**: Giappone, UAE, ecc.`
      }
    ]
  },
  {
    title: "Catalogo & Prodotti",
    slug: "catalogo",
    icon: Package,
    items: [
      { 
        title: "Struttura catalogo", 
        slug: "struttura-catalogo", 
        content: `# Struttura catalogo\n\nIl catalogo Ida è pensato per supportare la complessità dei listini B2B.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Prodotto Madre</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">L'entità principale (es. "Camicia Oxford in Lino"). Mantiene info generali, descrizione AI, categoria e media base.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Varianti (SKU)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Le declinazioni acquistabili (es. "Taglia L, Colore Blu"). Ogni variante richiede SKU univoco, inventario e prezzo.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Opzioni</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Le dimensioni che generano le varianti. Ad esempio: l'opzione "Taglia" contenente [S, M, L, XL].</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Attributi</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Informazioni descrittive (es. "Materiale: Cotone") utili per i filtri, ma che non influiscono sullo stock.</p>\n  </div>\n</div>`
      },
      { 
        title: "Dati richiesti e AI", 
        slug: "dati-richiesti", 
        content: `# Dati richiesti e AI Generativa\n\nPer pubblicare un prodotto e farlo approvare da Ida Genesis, è essenziale fornire dati accurati.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-900/30 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-red-900 dark:text-red-400 mb-3 flex items-center gap-2">Dati Obbligatori</h4>\n    <ul className="space-y-2 text-[14px] text-red-800 dark:text-red-200/80 m-0 p-0 list-none">\n      <li>• Titolo prodotto ed EAN/SKU</li>\n      <li>• Categoria merceologica</li>\n      <li>• Immagine 1000x1000px su fondo neutro</li>\n      <li>• Prezzo netto B2B</li>\n      <li>• Peso logistico e dimensioni imballo</li>\n      <li>• Autocertificazione Made in Italy</li>\n    </ul>\n  </div>\n  <div className="p-5 bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-900/30 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-emerald-900 dark:text-emerald-400 mb-3 flex items-center gap-2">Dati Raccomandati</h4>\n    <ul className="space-y-2 text-[14px] text-emerald-800 dark:text-emerald-200/80 m-0 p-0 list-none">\n      <li>• Minimo 4 foto + 1 Video</li>\n      <li>• Tier pricing (sconti a scaglioni)</li>\n      <li>• HS Code (Codice Doganale) pre-inserito</li>\n      <li>• Certificazioni (DOP, Bio, ISO)</li>\n      <li>• Documentazione di tracciabilità PDF</li>\n    </ul>\n  </div>\n</div>\n\n## Generazione testi con AI\nNon perdere tempo a scrivere descrizioni lunghe. Il nostro sistema integrato usa modelli LLM avanzati:\n1. Inserisci 3-4 bullet points (es. "pelle pregiata, cucito a mano, design elegante").\n2. Clicca **"Genera con AI"**.\n3. L'AI restituirà una descrizione B2B professionale formattata, tradotta in automatico in tutte le lingue dei mercati attivi.`
      },
      { 
        title: "Workflow di Approvazione", 
        slug: "ida-genesis", 
        content: `# Workflow di Approvazione (Ida Genesis)\n\nOgni prodotto inserito passa per il nostro motore di compliance, **Ida Genesis**, prima di andare online.\n\n## Fasi del controllo\n\n<div className="steps-list">\n  <div className="step-item" data-step="1">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Verifica Base & Made in Italy</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Controllo della completezza dei campi, coerenza delle immagini e validazione dell'autocertificazione d'origine.</p>\n  </div>\n  <div className="step-item" data-step="2">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Estrazione AI & Certificazioni</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Prometheux.ai legge i documenti PDF allegati per validare claim come "100% Bio" o "DOP", bloccando dichiarazioni false.</p>\n  </div>\n  <div className="step-item" data-step="3">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Restrizioni Doganali (HS Code)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">L'algoritmo incrocia l'HS Code con i mercati che hai attivato. Se vendi salumi negli USA, richiede automaticamente i flag per la normativa FDA.</p>\n  </div>\n  <div className="step-item" data-step="4">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Esito</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Il prodotto passa in "Approvato" (visibile) o "Richiesta Modifiche" (ti verrà indicato esattamente cosa correggere).</p>\n  </div>\n</div>`
      },
      { 
        title: "Import massivo e Integrazioni", 
        slug: "import-integrazioni", 
        content: `# Import massivo e Integrazioni\n\nSe hai cataloghi estesi, l'inserimento manuale non è l'unica via.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Import CSV / Excel</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Scarica il template ufficiale dalla dashboard. Puoi caricare centinaia di prodotti e varianti in un clic, mappare le colonne e gestire lo stock massivamente.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Plugin E-Commerce</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Connettori nativi per Shopify, WooCommerce e Magento. I prodotti si sincronizzano su Ida e gli ordini B2B ritornano nel tuo gestionale.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm md:col-span-2">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Integrazioni ERP & API</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Per architetture complesse (SAP, Dynamics, Akeneo PIM), esponiamo API REST/GraphQL documentate e offriamo supporto tecnico dedicato.</p>\n  </div>\n</div>`
      },
    ]
  },
  {
    title: "Vendita B2B",
    slug: "vendita-b2b",
    icon: Briefcase,
    items: [
      { 
        title: "Listini, Prezzi e MOQ", 
        slug: "listini-moq", 
        content: `# Listini, Prezzi e MOQ\n\nIda espone funzionalità B2B native per permetterti strategie commerciali complesse.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Listini Netti</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Tutti i prezzi inseriti si intendono IVA esclusa. Il motore di check-out calcolerà il Reverse Charge UE o l'export Art.8 in automatico.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Tier Pricing</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Offri incentivi sui volumi. Es: 1-10 pz = 100€, 11-50 pz = 90€, 50+ pz = 75€.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Minimum Order Quantity (MOQ)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Proteggi la marginalità impedendo ordini troppo piccoli. Puoi applicare il MOQ sul singolo SKU o imporre un valore minimo per carrello.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Listini Dedicati</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Crea un listino "Gold" con il 20% di sconto globale e assegnalo solo a specifici Company Account (i tuoi distributori storici).</p>\n  </div>\n</div>`
      },
      { 
        title: "Preventivi e Negoziazione", 
        slug: "rfq", 
        content: `# Preventivi e Negoziazione (RFQ)\n\nNel B2B, l'acquisto non è sempre a prezzo di listino. I buyer possono inviarti una **Request for Quotation (RFQ)** per ordini fuori standard o per negoziare.\n\n## Flusso della Negoziazione\n\n<div className="steps-list">\n  <div className="step-item" data-step="1">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Ricezione RFQ</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Il buyer seleziona i prodotti, le quantità (magari 10 pallet) e chiede una quotazione spedizione inclusa.</p>\n  </div>\n  <div className="step-item" data-step="2">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Creazione Proposta</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Dalla dashboard, puoi applicare uno sconto forfettario, aggiungere i costi logistici doganali e inserire una scadenza di validità al preventivo.</p>\n  </div>\n  <div className="step-item" data-step="3">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Chat Integrata (Lara AI)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Puoi contrattare i dettagli tramite la chat interna, che traduce istantaneamente i messaggi tra italiano e la lingua del buyer.</p>\n  </div>\n  <div className="step-item" data-step="4">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1">Conversione in Ordine</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Appena il buyer accetta, l'RFQ diventa un ordine in attesa di pagamento. Nessun inserimento manuale richiesto.</p>\n  </div>\n</div>`
      }
    ]
  },
  {
    title: "Ordini & Spedizioni",
    slug: "ordini-logistica",
    icon: Truck,
    items: [
      { 
        title: "Gestione Ordini", 
        slug: "gestione-ordini", 
        content: `# Gestione Ordini\n\nIl ciclo di vita di un ordine su Ida è strutturato per darti pieno controllo.\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Nuovo Ordine</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Ricevi la notifica. I fondi del buyer sono già stati autorizzati o bloccati in Escrow. Zero rischio di insolvenza.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Presa in Carico</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Accetta l'ordine entro 24/48h. Il sistema scala automaticamente l'inventario.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Documenti Automatici</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">La piattaforma genera la Fattura Proforma e la Packing List, essenziali se spedisci fuori dall'Unione Europea.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Tracking</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Appena affidi la merce, inserisci il tracking. Se usi Ida Shipping, si aggiorna da solo e notifica il buyer.</p>\n  </div>\n</div>`
      },
      { 
        title: "Spedizioni e Dogana", 
        slug: "dogana", 
        content: `# Spedizioni, Dogana e Incoterms\n\nLa logistica internazionale è complessa, ma Ida ti offre le soluzioni chiavi in mano.\n\n## Modalità di spedizione\n\n<div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Ida Shipping (Raccomandato)</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Sfrutta le nostre tariffe negoziate con DHL, UPS e FedEx. Generi l'etichetta in dashboard e prenoti il ritiro dal tuo magazzino.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Spedizione Propria</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Usi il tuo corriere di fiducia. Ti richiediamo solo di aggiornare la dashboard con il tracking number per sbloccare i tuoi pagamenti.</p>\n  </div>\n</div>\n\n## Incoterms supportati\nGestiamo nativamente il calcolo dei costi al check-out per le rese più sicure:\n- **DAP (Delivered at Place):** Tu paghi il corriere fino a destinazione. Il buyer paga dazi e tasse alla dogana del suo paese.\n- **DDP (Delivered Duty Paid):** Il sistema riscuote tasse e dazi al check-out; il pacco arriva al buyer "liscio" senza blocchi o sorprese. Altamente raccomandato per gli USA.`
      }
    ]
  },
  {
    title: "Pagamenti",
    slug: "finanza",
    icon: CreditCard,
    items: [
      { 
        title: "Pagamenti e Payout", 
        slug: "payout", 
        content: `# Pagamenti, Payout e Sicurezza\n\nIl marketplace garantisce i flussi finanziari tramite un provider certificato (Stripe), eliminando il rischio di credito.\n\n<div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-8 not-prose">\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Escrow dei Fondi</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Il buyer paga al checkout. I soldi restano al sicuro finché non inserisci la prova di spedizione. Nessuno scappa con la cassa.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Net Terms Assicurati</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">Se un buyer VIP gode di pagamenti a 60 giorni, Ida assicura il credito e tu ricevi comunque il tuo payout puntuale.</p>\n  </div>\n  <div className="p-5 bg-white dark:bg-[#111111] border border-zinc-200 dark:border-zinc-800/80 rounded-xl shadow-sm">\n    <h4 className="text-[14px] font-semibold text-zinc-900 dark:text-white mb-1.5">Payout Schedulati</h4>\n    <p className="text-[13px] text-zinc-600 dark:text-zinc-400 leading-relaxed m-0">I tuoi guadagni vengono bonificati automaticamente sul tuo IBAN aziendale su base settimanale o mensile.</p>\n  </div>\n</div>\n\n## Fatturazione e Reportistica\n- Ogni transazione produce un log contabile scaricabile (CSV).\n- Le commissioni Ida vengono riassunte in una fattura elettronica mensile pulita, facile da passare al tuo commercialista.\n- Nessuna confusione in caso di ordine multi-vendor: tu ricevi e fatturi solo per i prodotti che hai effettivamente spedito.`
      }
    ]
  }
]